### ISSUE TITLE
[Enhancement] Support setting dependencies field for KRM KCL Spec to add external dependency code

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/krm-kcl#63]
## Enhancement

Support setting dependencies field for KRM KCL Spec to add external dependency code. For example

```yaml
apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: set-annotation
spec:
  source: # Omit the source field
  # The format of the `dependencies` field is same as the `[dependencies]` in the `kcl.mod` file
  dependencies:
    k8s = 1.29
    konfig = { git = "https://github.com/awesome-kusion/konfig.git", tag = "v0.0.1" }
    mypackage = {oci = "oci://ghir.io/foo/bar", tag = "v0.1.0"}
```
